type: "vapor"
swift_version: "4.2.0"
run_parameters: "serve --port 8080 --hostname 0.0.0.0"
config:
  staging:
    CKPD_API_HOST: "globalweb-api-staging.ckpd.co"
    # CKPD_API_ANONYMOUS_TOKEN: "" # Inject via CLI - https://docs.vapor.cloud/configuration/vapor/custom-config/#cli
  production:
    CKPD_API_HOST: "global-api.cookpad.com"
    # CKPD_API_ANONYMOUS_TOKEN: "" # Inject via CLI - https://docs.vapor.cloud/configuration/vapor/custom-config/#cli